export const selectUserData = state => state.user.userData;
export const selectIsLoggedIn = state => state.user.isLoggedIn;
export const selectIsRefreshing = state => state.user.isRefreshing;
export const selectIsAuthModalOpen = state => state.user.isAuthModalOpen;
export const selectErrorStatus = state => state.user.errorStatus;
export const selectVerifiedEmail = state => state.user.verifiedEmail;
export const selectOrders = state => state.user.orders;
export const selectDelivery = state => state.user.delivery;
export const selectFavorites = state => state.user.favorites;
